// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDezEWZFaKDp2ZhHp6uikOBhMeh3cUn0ag',
    appId: '1:505157649490:android:28d591cf4236be62774b8b',
    messagingSenderId: '505157649490',
    projectId: 'auth-project-a809d',
    storageBucket: 'auth-project-a809d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlg6x9Iw5DTYxDjMVxktAW45D9FS1euOY',
    appId: '1:505157649490:ios:f09e8bb840e8cd47774b8b',
    messagingSenderId: '505157649490',
    projectId: 'auth-project-a809d',
    storageBucket: 'auth-project-a809d.appspot.com',
    androidClientId:
        '505157649490-8rv67g2rbpaedm0sabfs84o0or3eb9ia.apps.googleusercontent.com',
    iosClientId:
        '505157649490-cn8vc4li11o2hmusgm5gjl0cgn42apj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudOperations',
  );
}
